# !/usr/bin/python
# -*- coding:utf-8 -*-

KEY_SESSION_USER = '_USER'  # 用户
KEY_SESSION_USER_MENU = '_USER_MENU'  # 用户菜单
KEY_SESSION_MEMBER = '_MEMBER'  # 前台登录会员
KEY_MEMBER_CODE = '_MEMBER_CODE'  # 会员CODE

KEY_ADMINISTRATIVE_DIVISION = '_ADMINISTRATIVE_DIVISION'  # 行政区划缓存
KEY_CODE_VEHICLE_ATTRIBUTE = '_CODE_VEHICLE_ATTRIBUTE'  # 车辆属性

# 系统自增型CODE
KEY_INCREASE_UPLOAD_FILE = '_INCREASE_UPLOAD_FILE'  # 文件自增CODE
KEY_INCREASE_USER = '_INCREASE_USER'  # 用户自增CODE



KEY_ALLOW_PROCESS_ACCURATE_STATISTICS = '_ALLOW_PROCESS_ACCURATE_STATISTICS'  # 标记后台任务是否可以处理正确率数据
KEY_ALLOW_PROCESS_DOCKING_STATISTICS = '_ALLOW_PROCESS_DOCKING_STATISTICS'  # 标记后台任务是否可以处理对接数据