# !/usr/bin/python
# -*- coding:utf-8 -*-


# 系统上传文件类别
CATEGORY_UPLOAD_FILE_IMG_TXT = 4  # 富文本图片
CATEGORY_CERTIFICATE_UE = 9  # UEditor
CATEGORY_UPLOAD_FILE_OTHER = 99  # 其他图片
CATEGORY_UPLOAD_FILE_LIST = [
    CATEGORY_UPLOAD_FILE_IMG_TXT,
    CATEGORY_UPLOAD_FILE_OTHER
]
CATEGORY_UPLOAD_FILE_DICT = {
    CATEGORY_UPLOAD_FILE_IMG_TXT: '富文本图片',
    CATEGORY_UPLOAD_FILE_OTHER: '其他'
}

# 用户状态
STATUS_USER_ACTIVE = 1
STATUS_USER_INACTIVE = 2
STATUS_USER_LIST = [STATUS_USER_ACTIVE, STATUS_USER_INACTIVE]
STATUS_USER_DICT = {
    STATUS_USER_ACTIVE: '活动的',
    STATUS_USER_INACTIVE: '锁定的'
}

# 性别
SEX_NONE = 0
SEX_MALE = 1
SEX_FEMALE = 2
SEX_LIST = [SEX_NONE, SEX_MALE, SEX_FEMALE]
SEX_DICT = {
    SEX_NONE: '无',
    SEX_MALE: '男',
    SEX_FEMALE: '女'
}

# 角色状态
STATUS_ROLE_ACTIVE = 1
STATUS_ROLE_INACTIVE = 2
STATUS_ROLE_LIST = [STATUS_ROLE_ACTIVE, STATUS_ROLE_INACTIVE]
STATUS_ROLE_DICT = {
    STATUS_ROLE_ACTIVE: '活动的',
    STATUS_ROLE_INACTIVE: '锁定的'
}

STATUS_INACTIVE = 0  # 禁用状态
STATUS_ACTIVE = 1  # 启用状态
STATUS_LIST = [STATUS_ACTIVE, STATUS_INACTIVE]
STATUS_DICT = {
    STATUS_ACTIVE: '启用',
    STATUS_INACTIVE: '禁用'
}

STATUS_SUBJECT_ACTIVE=0
STATUS_SUBJECT_INACTIVE=1


